---
format: 
  docx:
    reference-doc: my_styles.docx
    number-sections: true
title: "EBASE manuscript"
bibliography: refs.bib
csl: limnology-and-oceanography.csl
author: 
  - Marcus W Beck:
      email: mbeck@tbep.org
      institute: [TBEP]
      correspondence: true
  - Jill M Arriola:
      email: jva5648@psu.edu 
      institute: [PSU]
      correspondence: false
  - Maria Hermann:
      email: mxh367@psu.edu
      institute: [PSU]
      correspondence: false
  - Raymond G Najjar:
      email: rgn1@psu.edu
      institute: [PSU]
      correspondence: false
 
institute:
  - TBEP: Tampa Bay Estuary Program, St. Petersburg, Florida 33701 USA
  - PSU: Pennsylvania State University, University Park, Pennsylvania 16802 USA

filters: 
  - templates/scholarly-metadata.lua
  - templates/author-info-blocks.lua
  
execute: 
  echo: false
  warning: false
  ft.keepnext: false
  ft.align: left
---

```{r, results = 'hide'}
library(knitr)
library(here)
library(flextable)

```

## Abstract {.unnumbered}

*Key words*: 

## Introduction

* Overview of metabolism - importance
* Existing methods: Odum/WtRegDO, BASEmetab, references in @Grace15, applications to lakes and streams
* Applications to estuaries - challenges
* Goals and objectives

## Materials and Procedures

* EBASE theory
* EBASE R package

## Assessment

* Comparison with Odum and BASEmetab: Fwoxy Appalachicola
* Comparison with Odum and BASemetab: Apalachicola
* Sensitivity analyses:
     * optimization length
     * priors
* Application to representative NERR sites

## Discussion

## Comments and Recommendations

## Acknowledgments {.unnumbered}

<!-- \newpage -->

## Figures {.unnumbered}

Figure 1: Fwoxy comparisons

Figure 2: Apalachicola comparisons

Figure 3: Sensitivity analyses

Figure 4: NERRS application

<!-- \newpage  -->

## Tables {.unnumbered}

Table 1: EBASE parameters and outputs

Table 2: Summary stats of Fwoxy comparison

Table 3: Summary stats of Apalachicola comparison

Table 4: Key parameters form NERRS application

<!-- \newpage -->

## References {.unnumbered}
